### ISSUE TITLE
Error when building GFEM models

### ISSUE THREAD

**Issue by nestorcerpa** [buchanankerswell/kerswell_et_al_madnn#1]
The file assets/config/perplex-build-config seems not to be created and therefore create a looping error (see log below) :
[log-08-04-2024.txt](https://github.com/buchanankerswell/kerswell_et_al_rocmlm/files/14902663/log-08-04-2024.txt)

**Comment by buchanankerswell** [comment]
This was an old config on the main branch before I added HP02 and STX21 config files. I just merged the develop branch so it should work now on the main branch.
