### ISSUE TITLE
Issue for long names used as project names when running Perple_X

### ISSUE THREAD

**Issue by nestorcerpa** [buchanankerswell/kerswell_et_al_madnn#2]
There is an issue when automatically generating project names to build Perple_X models. 

Perple_X throws : "file/project names must be < 91 characters, try again" when reading project name and then the file build-config is not to be correctly read afterwards.

A solution may be to work with relative paths for this specific configuration. 

I'm attaching log files including the one when I specifically identified this error. 
[log-09-04-2024.txt](https://github.com/buchanankerswell/kerswell_et_al_rocmlm/files/14916428/log-09-04-2024.txt)
[log-perp-PYR-v128.txt](https://github.com/buchanankerswell/kerswell_et_al_rocmlm/files/14916429/log-perp-PYR-v128.txt)

and the corresponding build-config 
[build-config.txt](https://github.com/buchanankerswell/kerswell_et_al_rocmlm/files/14916438/build-config.txt)

**Comment by buchanankerswell** [comment]
Thanks for pointing this out. I was using absolute paths to keep things simple, but apparently Perple_X and MAGEMin have strict character limits for paths. I will refactor gfem.py to use relative paths.

**Comment by buchanankerswell** [comment]
This is now fixed in commit [02b5b60](https://github.com/buchanankerswell/kerswell_et_al_rocmlm/commit/02b5b605bdb1265abd19b30a684c7685040b9fce).
